mysql:
  host: 127.0.0.1
  port: 3306
  database: database
  username: user
  password: pass

settings:
  discordWebhookURL: "WEBHOOKURL"
  dailyReportTime: "12:00"

permission:
  staff: staffmanager.staff

banSystem:
  litebans: false # yakında
  advancedban: true
