name: MStaff
version: '1.0-SNAPSHOT'
main: net.cengiz1.mstaff.MStaff
api-version: '1.20'
commands:
  staffmanager:
    description: "Yetkili komutları"
    usage: "/staff <playerName> veya /staff senddiscord"

permissions:
  staffmanager.staff:
    description: "Yetkili komutlarını kullanma izni"
    default: op
